### PR TITLE
Update FPM version, builds for Ubuntu Jammy and Noble

### LINKED ISSUE #10: Ubuntu Jammy and Ubuntu Noble releases
Is there a chance of having a a Jammy and Noble release of this image please?

I can try to provide a PR for it, but I wanted to make sure first that this project is still active.

### PR DESCRIPTION
**Pull request by weakcamel**
Closes #10

### CODE REVIEW

**Comment by alanfranz** [comment]
I think this wasn't really tested (e.g. Jammy wouldn't build without a fix, and some distros were very old). I have now updated the repo with the most recent version and setup GHA. I still need to properly push images to docker hub btw, stay tuned.

**Comment by alanfranz** [comment]
@weakcamel I have added a GHA workflow and now current images are pushed to docker hub, let me know if you encounter issues.

**Comment by weakcamel** [comment]
Thank you!

> I think this wasn't really tested

Indeed, it wasn't - sorry about that. It wasn't very clear to me how is the content of repo supposed to be tested, where does the `distributions.yml`'s data go (I couldn't find any references to it) so if the general direction turned out to be sensible, I was going to ask about that in the PR.

Thanks for finishing it off for me! I'll give those images a spin next week and let you know.

**Comment by aframachines** [comment]
This project exists since before github actions existed; distributions.yml
was used in my private jenkins instance.

Now everything should be clear and public! Thanks for your interest.

**Comment by weakcamel** [comment]
I tried those updated images this week (Focal and Jammy versions) and they worked like a charm.

**Pull request closed without merging**
